version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "5173:5173"
    env_file:
      - .env
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./start-nginx.sh:/start-nginx.sh
    entrypoint: [ "/bin/bash", "/start-nginx.sh" ]
    depends_on:
      - web

volumes:
  web:
  nginx:
